#include "Interaction/DetailModels.h"
#include "Persistence/DisplayProfiles.h"
#include "Interaction/AppSwitchPolicy.h"
#include "Interaction/DashboardModel.h"
#include "Persistence/Settings.h"
#include "Composition/DockGeometry.h"
#include "Animation/MotionEngine.h"
#include "Animation/ArtworkHandoff.h"
#include <sstream>
#include <iostream>
#include <stdexcept>
using namespace nexus;
static int checks=0;
static void test(bool pass,const char* label){++checks;if(!pass)throw std::runtime_error(label);}
int main(){try{
    FocusClock c;test(c.displayed(0)==1500,"focus default");c.toggle(10);test(c.displayed(70)==1440,"elapsed wall clock");c.toggle(70);test(c.displayed(700)==1440,"pause holds");c.toggle(800);test(!c.tick(2239),"does not finish early");test(c.tick(2240),"finish resumes remainder");test(!c.tick(3000),"completion only once");c.toggle(4000);test(c.running&&c.displayed(4000)==1500,"restart after completion");c.select(FocusClock::Mode::Break,0);test(c.displayed(0)==300,"break duration");c.select(FocusClock::Mode::Stopwatch,0);c.toggle(10);test(c.displayed(3610)==3600&&!c.tick(9000),"stopwatch unbounded");c.reset(9000);test(!c.running&&c.displayed(9000)==0,"stopwatch reset");
    test(classifyMedia(1,L"browser")==MediaKind::Music,"OS music wins");test(classifyMedia(2,L"Spotify")==MediaKind::Video,"OS video wins");test(classifyMedia(0,L"Spotify.exe")==MediaKind::Music,"known music app");test(classifyMedia(0,L"chrome.exe")==MediaKind::Unknown,"never guess browser content");
    HitTarget hit{Action::Play,10,10,30,30};test(hit.contains(10,10)&&!hit.contains(40,40),"half-open hit bounds");hit.enabled=false;test(!hit.contains(20,20),"disabled action cannot hit");
    Settings settings;settings.hoverOpen=false;settings.hoverDelay=430;settings.mediaLayout=2;std::stringstream f;settings.write(f);auto copy=Settings::parse(f);test(!copy.hoverOpen&&copy.hoverDelay==430&&copy.mediaLayout==2,"new settings roundtrip");
    std::stringstream legacy("version 1\npreset 2\n");auto migrated=Settings::parse(legacy);test(migrated.version==Settings::currentVersion&&migrated.hoverOpen&&migrated.preset==2,"v1 migration");
    std::stringstream bounds("version 2\nhoverDelay 999\nmediaLayout -2\n");auto bounded=Settings::parse(bounds);test(bounded.hoverDelay==700&&bounded.mediaLayout==0,"settings clamp");
    bool rejected=false;try{std::stringstream bad("version 2\nhoverDelay");Settings::parse(bad);}catch(...){rejected=true;}test(rejected,"truncated value rejected");
    test(clockText(3661)==L"1:01:01"&&clockText(-1)==L"00:00","time formatting");
        Settings appearance;appearance.edge=1;appearance.theme=2;appearance.scale=110;appearance.material=2;appearance.glassTint=73;appearance.directAudio=false;appearance.compactWidth=176;appearance.startAtLogin=false;std::stringstream pref;appearance.write(pref);auto restored=Settings::parse(pref);test(restored.edge==1&&restored.theme==2&&restored.scale==110&&restored.material==2&&restored.glassTint==73&&!restored.directAudio&&restored.compactWidth==176&&!restored.startAtLogin,"v3 appearance roundtrip");
    for(int edge:{0,1,2})for(bool attached:{false,true})for(auto g:{geometry(IslandState::Compact),geometry(IslandState::Expanded)}){auto points=dockOutline(g.width,g.height,g.radius,edge,attached);test(points.size()>40,"curved polygon coverage");const double reach=shoulderShape(g.radius).width+.01;for(auto point:points)test(std::isfinite(point.x)&&std::isfinite(point.y)&&point.x>=-reach&&point.x<=g.width+reach&&point.y>=-reach&&point.y<=g.height+reach,"outline finite bounded");
        if(attached){double top=1e9;for(auto point:points)top=std::min(top,edge==1?g.width-point.x:edge==2?point.x:point.y);test(std::abs(top)<1e-9,"attached outline meets the screen edge");}auto origin=bodyOrigin(g.width,g.height,600,500,edge);test(edge==1?origin.x+g.width==600:edge==2?origin.x==0&&origin.y+g.height/2==250:origin.x+g.width/2==300,"edge anchored");
        // The left dock is the right dock reflected.
        if(edge==2){auto right=dockOutline(g.width,g.height,g.radius,1,attached);bool mirrored=right.size()==points.size();for(size_t i=0;mirrored&&i<points.size();++i)mirrored=std::abs(points[i].x-(g.width-right[i].x))<1e-9&&std::abs(points[i].y-right[i].y)<1e-9;test(mirrored,"left outline mirrors the right");}}
    MotionEngine motion;motion.edge=1;motion.target(IslandState::Compact,1);test(motion.reveal.target()==0,"right compact has no expanded content");motion.target(IslandState::Expanded,1.1);auto before=motion.width.sample(1.2);motion.target(IslandState::Compact,1.2);auto after=motion.width.sample(1.2);test(std::abs(before.position-after.position)<1e-9&&std::abs(before.velocity-after.velocity)<1e-9,"size reversal preserves momentum");
    auto order=defaultNavigation;int slot=0;moveNavigation(order,slot,-1);test(order==defaultNavigation&&slot==0,"first nav cannot move left");moveNavigation(order,slot,1);test(slot==1&&order[1]==0&&validNavigation(order),"nav swap retains identity and permutation");for(int n=0;n<50;++n)moveNavigation(order,slot,1);test(slot==pageCount-1&&validNavigation(order),"last nav cannot disappear");
    auto metrics=defaultMetrics;for(int i=0;i<100;++i){cycleMetric(metrics,i%3);test(metrics[0]!=metrics[1]&&metrics[1]!=metrics[2]&&metrics[0]!=metrics[2],"home metrics stay unique");}
    Settings personalized;personalized.navigation=order;personalized.homeMetrics=metrics;personalized.glanceRings=2;personalized.trackHandoff=false;std::stringstream ps;personalized.write(ps);auto persisted=Settings::parse(ps);test(persisted.navigation==order&&persisted.homeMetrics==metrics&&persisted.glanceRings==2&&!persisted.trackHandoff,"personal layout and handoff roundtrip");
    std::stringstream invalidLayout("version 4\nnav0 1\nnav1 1\nhome0 2\nhome1 2\n");auto repaired=Settings::parse(invalidLayout);test(repaired.navigation==defaultNavigation&&repaired.homeMetrics==defaultMetrics,"corrupt layout repairs without hiding controls");test(normalizedProgress(-1,10)==0&&normalizedProgress(12,10)==1&&normalizedProgress(1,0)==0,"ring progress clamp");
    Artwork red;red.width=red.height=1;red.pixels={0,0,255,255};Artwork blue=red;blue.pixels={255,0,0,255};Artwork green=red;green.pixels={0,255,0,255};ArtworkHandoff blend;blend.change(&red,0,0,false);blend.change(&blue,0,1,true);auto mid=blend.visible(1.12);test(mid[0]>0&&mid[2]>0&&mid[3]==255,"intermediate cover blend");blend.change(&green,0,1.12,true);test(blend.visible(1.12)==mid,"interrupted handoff preserves visible composite");test(blend.visible(3)[1]==255,"handoff settles to latest cover");blend.change(&red,0,4,false);test(blend.visible(4)[2]==255,"reduced motion artwork changes immediately");for(int i=0;i<100;++i){double now=5+i*.01;auto before=blend.visible(now);blend.change(i%2?&red:&blue,0,now,true);test(before==blend.visible(now),"rapid tracks do not flash old cover");}test(blend.to.size()==256*256*4&&blend.from.size()==blend.to.size(),"handoff storage bounded");
    MotionEngine choreography;choreography.target(IslandState::Expanded,1);test(choreography.visibility(1).position==0,"content starts hidden until geometry can hold it");for(int i=0;i<500;++i){double t=1+i*.002;auto p=choreography.visibility(t);test(std::isfinite(p.position)&&p.position>=0&&p.position<=1.001,"geometry-gated opacity bounded");if(choreography.height.sample(t).position<230)test(p.position==0,"no expanded content under traveling artwork");}choreography.target(IslandState::Compact,2);test(choreography.visibility(2,true).position==0,"compact header does not flash at expanded width");test(choreography.visibility(5,true).position>.99,"compact header settles visible");
    test(volumeAt(-500,58,284)==0&&volumeAt(58,58,284)==0&&volumeAt(200,58,284)==50&&volumeAt(500,58,284)==100&&volumeAt(1,0,0)==0,"volume slider coordinates and clamping");
    for(bool enabled:{false,true})for(bool pinned:{false,true})for(bool dragging:{false,true})for(bool dropping:{false,true})test(AppSwitchPolicy::collapse(enabled,pinned,dragging,dropping)==(enabled&&!pinned&&!dragging&&!dropping),"app switching preserves pinned and active drags");
    test(AppSwitchPolicy::fullscreen(0,0,1920,1200,0,0,1920,1200),"fullscreen exact display");
    test(!AppSwitchPolicy::fullscreen(0,0,1920,1152,0,0,1920,1200),"maximized work area is not fullscreen");
    test(AppSwitchPolicy::fullscreen(-1920,0,0,1080,-1920,0,0,1080),"negative monitor coordinates");
    Settings taskPrefs;taskPrefs.collapseOnAppSwitch=false;taskPrefs.wheelVolume=true;std::stringstream taskStream;taskPrefs.write(taskStream);auto taskCopy=Settings::parse(taskStream);test(!taskCopy.collapseOnAppSwitch&&taskCopy.wheelVolume,"multitasking preferences persist");
    test(!AppSwitchPolicy::fullscreen(0,0,1920,1200,0,0,1920,1200,true,false),"decorated monitor-sized browser stays visible");
    test(!AppSwitchPolicy::fullscreen(0,0,1920,1200,0,0,1920,1200,false,true),"maximized browser stays visible with auto-hidden taskbar");
    ScrubGesture scrub;scrub.begin(190,380,0,100);test(scrub.active&&scrub.value==50,"seek starts under pointer");scrub.move(228,0,380,0,100);test(std::abs(scrub.value-60)<1e-9,"direct seeking");scrub.move(266,80,380,0,100);test(std::abs(scrub.value-61.2)<1e-9,"fine seeking uses reduced gain without jumps");scrub.move(-999,0,380,0,100);test(scrub.value==0,"seek clamps before start");scrub.begin(1,0,0,0);test(!scrub.active,"unavailable timeline cannot seek");
    RouteConfirmation route;test(!route.observe(L"speakers"),"initial audio enumeration is silent");test(!route.observe(L"speakers"),"volume does not trigger headphone animation");test(route.observe(L"headphones"),"confirmed route change triggers once");test(!route.observe(L"headphones"),"duplicate route events coalesce");test(!route.observe(L""),"missing route is not a confirmed output");
    Settings wide;wide.uiMode=0;wide.compactWidth=560;wide.compactClock=true;wide.compactVolume=false;wide.shelfPeek=false;std::stringstream ws;wide.write(ws);auto wc=Settings::parse(ws);test(wc.uiMode==0&&wc.compactWidth==560&&wc.compactClock&&!wc.compactVolume&&!wc.shelfPeek,"v5 compact preferences roundtrip");
    std::stringstream limit("version 5\ncompactWidth 99999\nuiMode -1\n");auto limited=Settings::parse(limit);test(limited.compactWidth==560&&limited.uiMode==0,"wide bounds safe");
    DisplayProfiles profiles;Settings first;first.horizontalOffset=-120;first.compactWidth=420;first.scale=110;profiles.preferred="panel-A";profiles.remember("panel-A",first);Settings second;second.edge=1;second.verticalOffset=20;profiles.remember("panel-B",second);std::stringstream ds;profiles.write(ds);auto dp=DisplayProfiles::read(ds);Settings restoredDisplay;test(dp.preferred=="panel-A"&&dp.restore("panel-B",restoredDisplay)&&restoredDisplay.edge==1&&restoredDisplay.verticalOffset==20,"display identity persistence independent of enumeration");test(dp.restore("panel-A",restoredDisplay)&&restoredDisplay.horizontalOffset==-120&&restoredDisplay.compactWidth==420&&restoredDisplay.scale==110,"returning display restores its geometry");test(!dp.restore("unplugged",restoredDisplay)&&restoredDisplay.compactWidth==420,"unknown display leaves preferences untouched");std::stringstream truncated("display_profiles 1\n\"panel-A\"\n\"panel-A\" 0 2");test(DisplayProfiles::read(truncated).placements.empty(),"partial profile rejected");
    MotionEngine live;live.live=true;live.target(IslandState::LiveActivity,0);test(live.width.target()==360&&live.height.target()==154&&live.visibility(3).position>.99,"small live card reaches visible state");live.compactWidth=72;live.target(IslandState::Compact,3);test(live.width.target()==72&&live.visibility(6,true).position>.99,"mini returns to compact silhouette");
    for(int hz:{60,90,120,144,165,240}){Spring spring;spring.retarget(560,0,preset(MotionPreset::Fluid));double duration;auto curve=spring.curve(0,duration);for(int frame=0;frame<int(duration*hz);++frame){double t=double(frame)/hz;auto it=std::upper_bound(curve.begin(),curve.end(),t,[](double time,const CubicSegment& segment){return time<segment.time;});if(it!=curve.begin())--it;double u=t-it->time,rendered=it->p+u*(it->v+u*(it->quadratic+u*it->cubic));test(std::abs(rendered-spring.sample(t).position)<.004,"compositor spring sampling accurate at display cadence");}}
    std::cout<<"PASS "<<checks<<" dashboard, classification, timer, and migration checks\n";return 0;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
